version: 2
workflows:
  version: 2
  test:
    jobs:
    - test-2.5
    - test-2.4
    - test-2.3
jobs:
  test-2.5: &test-template
    docker:
    - image: circleci/ruby:2.5.1

    working_directory: ~/repo

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "Gemfile.lock" }}
        - v1-dependencies-

    - run:
        name: install dependencies
        command: |
          bundle install --jobs=4 --retry=3 --path vendor/bundle

    - save_cache:
        paths:
        - ./vendor/bundle
        key: v1-dependencies-{{ checksum "Gemfile.lock" }}

    - run:
        name: run tests
        command: |
          bundle exec rake test
  test-2.4:
    <<: *test-template
    docker:
    - image: circleci/ruby:2.4.4
  test-2.3:
    <<: *test-template
    docker:
    - image: circleci/runy:2.3.7
