version: 2
jobs:
  build:
    docker:
    - image: circleci/ruby:2.5.1
      environment:
        BUNDLE_JOBS: 3
        BUNDLE_RETRY: 3
        BUNDLE_PATH: vendor/bundle
    steps:
    - checkout

    - run:
        name: Which bundler?
        command: bundle -v

    - restore_cache:
        keys:
        - ruby-bundle-v2-{{ checksum "Gemfile.lock" }}

    - run:
        name: Bundle Install
        command: bundle check || bundle install

    - save_cache:
        key: ruby-bundle-v2-{{ checksum "Gemfile.lock" }}
        paths:
        - vendor/bundle

    - run:
        command: |
          bundle exec rake test
